### ISSUE TITLE
Question 53 with wrong answer

### ISSUE THREAD

**Issue by yosoyoscar** [Vasu7389/ReactJs-Interview-Question-2023#7]
I believe answer for question 53 should be 'The output would be "You clicked 1 times"', rather than 'The output would be "You clicked 2 times"'.

**Comment by yosoyoscar** [comment]
Sorry, my mistake.

**Comment by Vasu7389** [comment]
No problem, anyways I will cross check :)

Thanks for reporting. Feel free to add more cool questions.
